### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by su8** [budRich/budRich.github.io#2]
Hello Nils,

The scrollbar in your blog blends with the solarized background and becomes invisible, can you fix that up ?

```css
scrollbar{width:8px;height:8px;background-color:#073642}
::-webkit-scrollbar-corner{background-color:#073642}
::-webkit-scrollbar-thumb{background:#002b36}
body{scrollbar-face-color:#002b36;scrollbar-track-color:#073642}
```

Cheers
